### ISSUE TITLE
The Drupal\user\Entity\User class does not correspond to an entity type

### ISSUE THREAD

**Issue by veugenio** [drupalauth/simplesamlphp-module-drupalauth#77] opened 2021-08-30 18:20 UTC
---
name: Bug report
about: The Drupal\user\Entity\User class does not correspond to an entity type
title: ''
labels: ''
assignees: ''

---

**Describe the bug**
When trying to test configured authentication sources (or directly via /simplesaml/module.php/core/authenticate.php?as=drupal-userpass) we got:
```
The Drupal\user\Entity\User class does not correspond to an entity type.
```
**To Reproduce**
Considering you have a Drupal site and the library configured:
1. Authenticate on Drupal site;
2. Go to 'Test authentication sources' (/simplesaml/module.php/core/authenticate.php);
3. 2. Click on 'drupal-userpass' authentication;

**Expected behavior**
User should be authenticated properly.

**Please complete the following information:**

- PHP version in use: PHP 7.4.16
- Drupal core version: 8.9.16
- drupalauth version: 1.8.1
- SimpleSAMLphp version: 1.18.8
- webserver version: Apache/2.4.38

**Additional context**
Full error message:
```
SimpleSAML\Error\Error: UNHANDLEDEXCEPTION

Backtrace:
1 www/_include.php:17 (SimpleSAML_exception_handler)
0 [builtin] (N/A)
Caused by: Drupal\Core\Entity\Exception\NoCorrespondingEntityClassException: The Drupal\user\Entity\User class does not correspond to an entity type.
Backtrace:
8 /app/docroot/core/lib/Drupal/Core/Entity/EntityTypeRepository.php:98 (Drupal\Core\Entity\EntityTypeRepository::getEntityTypeFromClass)
7 /app/docroot/core/lib/Drupal/Core/Entity/EntityBase.php:543 (Drupal\Core\Entity\EntityBase::load)
6 modules/drupalauth/lib/Auth/Source/External.php:160 (SimpleSAML\Module\drupalauth\Auth\Source\External::getUser)
5 modules/drupalauth/lib/Auth/Source/External.php:181 (SimpleSAML\Module\drupalauth\Auth\Source\External::authenticate)
4 lib/SimpleSAML/Auth/Source.php:208 (SimpleSAML\Auth\Source::initLogin)
3 lib/SimpleSAML/Auth/Simple.php:167 (SimpleSAML\Auth\Simple::login)
2 modules/core/www/authenticate.php:38 (require)
1 lib/SimpleSAML/Module.php:260 (SimpleSAML\Module::process)
0 www/module.php:10 (N/A)
```

**Comment by veugenio** [comment] 2021-08-30 18:25
Apparently, it is related to Drupal root.
Maybe this change, could help:
```
diff --git a/lib/Auth/Source/External.php b/lib/Auth/Source/External.php
index 6be7226..b73cdfc 100755
--- a/lib/Auth/Source/External.php
+++ b/lib/Auth/Source/External.php
@@ -153,10 +153,13 @@ class External extends Source
 
         if (!empty($drupaluid)) {
             // Load the user object from Drupal.
+            $originalDir = getcwd();
+            chdir($this->config->getDrupalroot());
             $drupaluser = User::load($uid);
             if ($drupaluser->isBlocked()) {
                 throw new Error('NOACCESS');
             }
+            chdir($originalDir);
 
             $requested_attributes = $this->config->getAttributes();
```

**Comment by RoSk0** [comment] 2021-09-24 10:03
Can you please provide your vhost configuration for Apache.

**Comment by RoSk0** [comment] 2023-11-07 21:48
Cannot reproduce.

Closing outdated.

**Closed by RoSk0** 2023-11-07 21:48 UTC
