### ISSUE TITLE
SLO Issue with IdP

### ISSUE THREAD

**Issue by GoogleCodeExporter** [drupalauth/simplesamlphp-module-drupalauth#15] opened 2015-03-12 21:12 UTC
```
What steps will reproduce the problem?
1. In the same browser (different tabs), sign into 2 SPs and the IdP. 
2. Initiate "Log Out" from the IdP (Drupal 7 Website)
3. You are only logged out from the IdP (Drupal 7 site), not the IdPs. 
4. If you initiate "Log Out" from any of the SPs, you are logged out of all 3 
SPs and the IdP (Drupal 7 site)

What is the expected output? What do you see instead?
Once logged out of the IdP (Drupal 7 site), I should be able to go to the SP 
tabs, and hit "refresh" and be redirected to a login page. That doesn't happen. 
I'm able to continue navigating throughout both SPs. 


What version of the product are you using? On what operating system?
I'm using the latest version of simpleSAMLphp on the IdP which is running a 
Drupal 7 website. 

Please provide any additional information below.


```

Original issue reported on code.google.com by `Phil.Gar...@gmail.com` on 19 Mar 2014 at 8:20

**Comment by johnbburg** [comment] 2016-06-21 03:14
#28 should resolve this.

**Comment by johnbburg** [comment] 2016-06-21 03:15
This is also a duplicate of #6.

**Closed** 2020-03-27 08:12 UTC
