### ISSUE TITLE
Autoloader issue with version 1.8-beta2

### ISSUE THREAD

**Issue by thursdayADG** [drupalauth/simplesamlphp-module-drupalauth#64] opened 2020-09-30 23:11 UTC
Drupal version 8.8.8

DrupalAuth version 1.8-beta-2
Simplesamlphp (install via composer) version: vendor/simplesamlphp/simplesamlphp (1.17.8)

simplesamlphp info:
<img width="550" alt="Screen Shot 2020-10-01 at 8 51 00 am" src="https://user-images.githubusercontent.com/69443491/94747850-48cf8e00-03c3-11eb-8298-fa6fac14be62.png">

Did a `composer require drupalauth/simplesamlphp-module-drupalauth 1.8.0-beta2`

The simplesamlphp session store is set to sql
```
  'store.type' => 'sql',
```

I haved added this to authsources.php
```
  'drupal-userpass' => array(
    'drupalauth:UserPass',

    // The filesystem path of the Drupal directory.
    'drupalroot' => '/var/www/mysite/docroot',

    // Whether to turn on debug
    'debug' => true,

    // Which attributes should be retrieved from the Drupal site.
    'attributes' => array(
      array('field_name' => 'uid', 'attribute_name' => 'uid'),
      array('field_name' => 'roles', 'attribute_name' => 'roles', 'field_property' => 'target_id'),
      array('field_name' => 'name', 'attribute_name' => 'cn'),
      array('field_name' => 'mail', 'attribute_name' => 'mail'),
      array('field_name' => 'field_first_name', 'attribute_name' => 'givenName'),
      array('field_name' => 'field_last_name', 'attribute_name' => 'sn'),
      array('field_name' => 'field_organization', 'attribute_name' => 'ou', 'field_property' => 'target_id'),
    ),
  ),
```

drupal-userpass shows as an authentication source:
<img width="963" alt="Screen Shot 2020-10-01 at 8 56 01 am" src="https://user-images.githubusercontent.com/69443491/94748429-a7e1d280-03c4-11eb-8d17-f88b15e7e6a0.png">

Clicking drupal-userpass takes me to the login page, where I enter any username and password, doesn't matter as the error
occurs regardless.

<img width="973" alt="Screen Shot 2020-10-01 at 9 05 43 am" src="https://user-images.githubusercontent.com/69443491/94748789-7cabb300-03c5-11eb-86ed-80f72126f5c3.png">

The resulting error from the login form submission:

Url: http://local.mystite.com/simplesaml/module.php/core/loginuserpass.php?

```
Warning: get_class() expects parameter 1 to be object, bool given in Drupal\Core\DrupalKernel->initializeSettings() (line 1072 of /var/www/mysite/docroot/core/lib/Drupal/Core/DrupalKernel.php).
Drupal\Core\DrupalKernel->initializeSettings(Object) (Line: 275)
Drupal\Core\DrupalKernel::createFromRequest(Object, 1, 'prod', 1, '/var/www/mysite/docroot') (Line: 25)
SimpleSAML\Module\drupalauth\DrupalHelper->bootDrupal('/var/www/mysite/docroot') (Line: 110)
SimpleSAML\Module\drupalauth\Auth\Source\UserPass->login('admin', '*****') (Line: 285)
SimpleSAML\Module\core\Auth\UserPassBase::handleLogin('_4f3d49dc1b2dcdcb278a73439c5c91c5cf5301cb15:http://local.mysite.com/simplesaml/module.php/core/as_login.php?AuthId=drupal-userpass&amp;ReturnTo=http%3A%2F%2Flocal.mysite.com%2Fsimplesaml%2Fmodule.php%2Fcore%2Fauthenticate.php%3Fas%3Ddrupal-userpass', 'admin', '*****') (Line: 83)
require('/var/www/mysite/vendor/simplesamlphp/simplesamlphp/modules/core/www/loginuserpass.php') (Line: 236)
SimpleSAML\Module::process() (Line: 9)
Warning: get_class() expects parameter 1 to be object, bool given in Drupal\Core\DrupalKernel->initializeSettings() (line 1087 of /var/www/mysite/docroot/core/lib/Drupal/Core/DrupalKernel.php).
Drupal\Core\DrupalKernel->initializeSettings(Object) (Line: 275)
Drupal\Core\DrupalKernel::createFromRequest(Object, 1, 'prod', 1, '/var/www/mysite/docroot') (Line: 25)
SimpleSAML\Module\drupalauth\DrupalHelper->bootDrupal('/var/www/mysite/docroot') (Line: 110)
SimpleSAML\Module\drupalauth\Auth\Source\UserPass->login('admin', '*****') (Line: 285)
SimpleSAML\Module\core\Auth\UserPassBase::handleLogin('_4f3d49dc1b2dcdcb278a73439c5c91c5cf5301cb15:http://local.mysite.com/simplesaml/module.php/core/as_login.php?AuthId=drupal-userpass&amp;ReturnTo=http%3A%2F%2Flocal.mysite.com%2Fsimplesaml%2Fmodule.php%2Fcore%2Fauthenticate.php%3Fas%3Ddrupal-userpass', 'admin', '*****') (Line: 83)
require('/var/www/mysite/vendor/simplesamlphp/simplesamlphp/modules/core/www/loginuserpass.php') (Line: 236)
SimpleSAML\Module::process() (Line: 9)
The website encountered an unexpected error. Please try again later.
InvalidArgumentException: The class finder must implement a "findFile" method. in Symfony\Component\ClassLoader\ApcClassLoader->__construct() (line 77 of /var/www/mysite/vendor/symfony/class-loader/ApcClassLoader.php).
Symfony\Component\ClassLoader\ApcClassLoader->__construct('drupal.class_loader.8.8.8.8.8.8.fcd90ee3042737ccddb1e417b2fb9ac8a5d78b2b922aa0b94333b1be9b23c608', 1) (Line: 1095)
Drupal\Core\DrupalKernel->initializeSettings(Object) (Line: 275)
Drupal\Core\DrupalKernel::createFromRequest(Object, 1, 'prod', 1, '/var/www/mysite/docroot') (Line: 25)
SimpleSAML\Module\drupalauth\DrupalHelper->bootDrupal('/var/www/mysite/docroot') (Line: 110)
SimpleSAML\Module\drupalauth\Auth\Source\UserPass->login('admin', '*****') (Line: 285)
SimpleSAML\Module\core\Auth\UserPassBase::handleLogin('_4f3d49dc1b2dcdcb278a73439c5c91c5cf5301cb15:http://local.mysite.com/simplesaml/module.php/core/as_login.php?AuthId=drupal-userpass&amp;ReturnTo=http%3A%2F%2Flocal.mysite.com%2Fsimplesaml%2Fmodule.php%2Fcore%2Fauthenticate.php%3Fas%3Ddrupal-userpass', 'admin', '*****') (Line: 83)
require('/var/www/mysite/vendor/simplesamlphp/simplesamlphp/modules/core/www/loginuserpass.php') (Line: 236)
SimpleSAML\Module::process() (Line: 9)
```

**Comment by thursdayADG** [comment] 2020-10-01 06:36
I don't appear to have access to link this issue to this PR: https://github.com/drupalauth/simplesamlphp-module-drupalauth/pull/65

**Comment by RoSk0** [comment] 2021-09-24 09:40
I have multiple working in production installations that never shown symptoms of a similar sorts. 

To work on an issue we need a repeatable process to replicate it. 

If anyone is still experiencing this issue please share your setup details and a process to replicate it. 

All merge requests that are suggesting to fix an issue without a proper steps to reproduce it, like #74 & #79, will be ignored.

**Comment by bartlangelaan** [comment] 2021-09-27 16:27
Hey @RoSk0, thanks for bringing this up.

I do indeed believe this is not an error that happens for everyone, but only happens when you use Drupal in a sometimes hackish way.

For example, we already load some Drupal files in the simplesamlphp config.php, so we can read from the settings.php. To make this happen, we require the autoloader in the simplesamlphp config.php.

By the time the drupalauth module is loaded, it uses `require_once` to load the autoloader. Because it was loaded before, only `TRUE` is returned, and the module crashes.

That is why MR #79 is, I think, the perfect fix. It should just _always_ load the autoloader, not only if it was never loaded before. Requiring the autoloader multiple times is supported by Drupal and Composer - it uses a singleton to never create the autoloader twice, it will return the same autoloader every time you require it.

So, to reproduce this, you just have to put a `require 'yourprojectroot/web/autoload.php';` somewhere in your simplesamlphp config.php. Simply changing `require_once` to `require` (see MR #79) will fix this, without changing anything for people that are not requiring the autoloader themselves.

**Comment by RoSk0** [comment] 2021-09-27 21:51
Thanks for the details @bartlangelaan !

This makes it easy to understand where the people are coming from, motivation and how to test. 

I will try find some time soon to test the change from #79.

In the meantime,is it possible for you to share your `config.php` or just explain the need to read Drupal's `settings.php` from it? I'm very interested to know what use cases exist out there.

**Comment by RoSk0** [comment] 2023-11-07 21:51
Closing outdated.

**Closed by RoSk0** 2023-11-07 21:51 UTC
