### ISSUE TITLE
Boot drupal will broke Drupal services

### ISSUE THREAD

**Issue by Oscaner** [drupalauth/simplesamlphp-module-drupalauth#75] opened 2021-07-29 01:50 UTC
PHP stack:

```log
[18-Mar-2021 07:43:40 UTC] Drupal\Component\Plugin\Exception\PluginNotFoundException: The "field_item:language" plugin does not exist. Valid plugin IDs for Drupal\Core\TypedData\TypedDataManager are:  in /mnt/www/html/xxx/docroot/core/lib/Drupal/Component/Plugin/Discovery/DiscoveryTrait.php on line 53 #0 /mnt/www/html/xxx/docroot/core/lib/Drupal/Component/Plugin/Discovery/DiscoveryCachedTrait.php(25): Drupal\Core\Plugin\DefaultPluginManager->doGetDefinition(Array, 'field_item:lang...', true)
#1 /mnt/www/html/xxx/docroot/core/lib/Drupal/Core/TypedData/TypedDataManager.php(248): Drupal\Core\Plugin\DefaultPluginManager->getDefinition('field_item:lang...')
#2 /mnt/www/html/xxx/docroot/core/lib/Drupal/Core/TypedData/DataDefinition.php(263): Drupal\Core\TypedData\TypedDataManager->getDefaultConstraints(Object(Drupal\Core\Field\TypedData\FieldItemDataDefinition))
#3 /mnt/www/html/xxx/docroot/core/lib/Drupal/Core/TypedData/DataDefinition.php(271): Drupal\Core\TypedData\DataDefinition->getConstraints()
#4 /mnt/www/html/xxx/docroot/core/lib/Drupal/Core/Field/BaseFieldDefinition.php(374): Drupal\Core\TypedData\DataDefinition->getConstraint('ComplexData')
#5 /mnt/www/html/xxx/docroot/core/modules/user/src/Entity/User.php(466): Drupal\Core\Field\BaseFieldDefinition->addPropertyConstraints('value', Array)
#6 /mnt/www/html/xxx/docroot/core/lib/Drupal/Core/Entity/EntityFieldManager.php(214): Drupal\user\Entity\User::baseFieldDefinitions(Object(Drupal\Core\Entity\ContentEntityType))
#7 /mnt/www/html/xxx/docroot/core/lib/Drupal/Core/Entity/EntityFieldManager.php(179): Drupal\Core\Entity\EntityFieldManager->buildBaseFieldDefinitions('user')
#8 /mnt/www/html/xxx/docroot/core/lib/Drupal/Core/Entity/EntityFieldManager.php(330): Drupal\Core\Entity\EntityFieldManager->getBaseFieldDefinitions('user')
#9 /mnt/www/html/xxx/docroot/core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php(1238): Drupal\Core\Entity\EntityFieldManager->getFieldDefinitions('user', 'user')
#10 /mnt/www/html/xxx/docroot/core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php(524): Drupal\Core\Entity\Sql\SqlContentEntityStorage->loadFromDedicatedTables(Array, false)
#11 /mnt/www/html/xxx/docroot/core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php(449): Drupal\Core\Entity\Sql\SqlContentEntityStorage->mapFromStorageRecords(Array)
#12 /mnt/www/html/xxx/docroot/core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php(415): Drupal\Core\Entity\Sql\SqlContentEntityStorage->getFromStorage(Array)
#13 /mnt/www/html/xxx/docroot/core/lib/Drupal/Core/Entity/EntityStorageBase.php(300): Drupal\Core\Entity\Sql\SqlContentEntityStorage->doLoadMultiple(Array)
#14 /mnt/www/html/xxx/docroot/core/lib/Drupal/Core/Entity/EntityStorageBase.php(250): Drupal\Core\Entity\EntityStorageBase->loadMultiple(Array)
#15 /mnt/www/html/xxx/docroot/core/lib/Drupal/Core/Entity/EntityBase.php(544): Drupal\Core\Entity\EntityStorageBase->load('211')
#16 /mnt/www/html/xxx/vendor/simplesamlphp/simplesamlphp/modules/drupalauth/lib/Auth/Source/External.php(156): Drupal\Core\Entity\EntityBase::load('211')
#17 /mnt/www/html/xxx/vendor/simplesamlphp/simplesamlphp/modules/drupalauth/lib/Auth/Source/External.php(299): SimpleSAML\Module\drupalauth\Auth\Source\External->getUser()
#18 /mnt/www/html/xxx/vendor/simplesamlphp/simplesamlphp/modules/drupalauth/www/resume.php(12): SimpleSAML\Module\drupalauth\Auth\Source\External::resume()
#19 /mnt/www/html/xxx/vendor/simplesamlphp/simplesamlphp/lib/SimpleSAML/Module.php(260): require('/mnt/www/html/m...')
#20 /mnt/www/html/xxx/vendor/simplesamlphp/simplesamlphp/www/module.php(10): SimpleSAML\Module::process()
```

**Comment by RoSk0** [comment] 2021-07-31 09:23
Thank you for the report.

It will be way more useful if you would add 

- PHP version in use
- Drupal core version
- SimpleSAMLphp version
-  webserver version
-  steps to reproduce the issue
- when/why it started to happen

**Comment by RoSk0** [comment] 2023-11-07 21:49
Cannot reproduce and not enough information.

Closing outdated.

**Closed by RoSk0** 2023-11-07 21:49 UTC
