### ISSUE TITLE
Class not found error after user logs in

### ISSUE THREAD

**Issue by bioschaf** [drupalauth/simplesamlphp-module-drupalauth#82] opened 2022-04-12 07:09 UTC
If a user is not logged at drupal, he gets a wsod after logging in before being redirected to the website.
If a user is logged in beforehand, all works just fine.

Error: Class 'Symfony\Component\HttpFoundation\ResponseHeaderBag' not found in Symfony\Component\HttpFoundation\Response->__construct() (Zeile 204 in /srv/www/htdocs/vendor/symfony/http-foundation/Response.php)

#0 /srv/www/htdocs/core/includes/errors.inc(165): Symfony\Component\HttpFoundation\Response->__construct()
#1 /srv/www/htdocs/core/includes/errors.inc(83): _drupal_log_error(Array, false)
#2 /srv/www/htdocs/core/includes/bootstrap.inc(346): _drupal_error_handler_real(2, 'Declaration of ...', '/srv/www/htdocs...', 93)
#3 /var/simplesamlphp/vendor/composer/ClassLoader.php(571): _drupal_error_handler(2, 'Declaration of ...', '/srv/www/htdocs...', 93, Array)
#4 /var/simplesamlphp/vendor/composer/ClassLoader.php(571): include()
#5 /var/simplesamlphp/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile('/srv/www/htdocs...')
#6 [internal function]: Composer\Autoload\ClassLoader->loadClass('Symfony\\Compone...')
#7 [internal function]: spl_autoload_call('Symfony\\Compone...')
#8 /srv/www/htdocs/vendor/symfony/http-foundation/Response.php(15): class_exists('Symfony\\Compone...')
#9 /var/simplesamlphp/vendor/composer/ClassLoader.php(571): include('/srv/www/htdocs...')
#10 /var/simplesamlphp/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile('/srv/www/htdocs...')
#11 [internal function]: Composer\Autoload\ClassLoader->loadClass('Symfony\\Compone...')
#12 /srv/www/htdocs/vendor/simplesamlphp/simplesamlphp/lib/SimpleSAML/XHTML/Template.php(32): spl_autoload_call('Symfony\\Compone...')
#13 /var/simplesamlphp/vendor/composer/ClassLoader.php(571): include('/srv/www/htdocs...')
#14 /var/simplesamlphp/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile('/srv/www/htdocs...')
#15 [internal function]: Composer\Autoload\ClassLoader->loadClass('SimpleSAML\\XHTM...')
#16 /srv/www/htdocs/vendor/simplesamlphp/simplesamlphp/lib/SimpleSAML/Utils/HTTP.php(1356): spl_autoload_call('SimpleSAML\\XHTM...')
#17 /srv/www/htdocs/vendor/simplesamlphp/saml2/src/SAML2/Compat/Ssp/Container.php(107): SimpleSAML\Utils\HTTP::submitPOSTData('https://xxx', Array)
#18 /srv/www/htdocs/vendor/simplesamlphp/saml2/src/SAML2/HTTPPost.php(54): SAML2\Compat\Ssp\Container->postRedirect('https://xxx', Array)
#19 /var/simplesamlphp/modules/saml/lib/IdP/SAML2.php(117): SAML2\HTTPPost->send(Object(SAML2\Response))
#20 [internal function]: SimpleSAML\Module\saml\IdP\SAML2::sendResponse(Array)
#21 /srv/www/htdocs/vendor/simplesamlphp/simplesamlphp/lib/SimpleSAML/IdP.php(290): call_user_func(Array, Array)
#22 /srv/www/htdocs/vendor/simplesamlphp/simplesamlphp/lib/SimpleSAML/IdP.php(337): SimpleSAML\IdP::postAuthProc(Array)
#23 [internal function]: SimpleSAML\IdP::postAuth(Array)
#24 /var/simplesamlphp/lib/SimpleSAML/Auth/Source.php(248): call_user_func(Array, Array)
#25 [internal function]: SimpleSAML\Auth\Source::loginCompleted(Array)
#26 /var/simplesamlphp/lib/SimpleSAML/Auth/Source.php(161): call_user_func(Array, Array)
#27 /var/simplesamlphp/modules/drupalauth/lib/Auth/Source/External.php(316): SimpleSAML\Auth\Source::completeAuth(Array)
#28 /var/simplesamlphp/modules/drupalauth/www/resume.php(12): SimpleSAML\Module\drupalauth\Auth\Source\External::resume()
#29 /var/simplesamlphp/lib/SimpleSAML/Module.php(266): require('/var/simplesaml...')
#30 /var/simplesamlphp/www/module.php(10): SimpleSAML\Module::process()
#31 {main}

**Comment by RoSk0** [comment] 2023-11-07 21:47
Cannot reproduce and not enough information.

Closing outdated.

**Closed by RoSk0** 2023-11-07 21:47 UTC
